#!/usr/bin/env node
'use strict';
var readline = require('readline');
var fs = require('fs');
var file = process.argv[2];
var options = { encoding: 'utf8' };

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

fs.readFile(file, options, function (err, contents){
	var obj = JSON.parse(contents);
	var startRoom = findStartRoom(obj.rooms);
	var currentRoom = startRoom;
	var finishRoom = findFinishRoom(obj.rooms);
	currentRoom = nextRoom(currentRoom, 'north');
	// console.log(currentRoom);
	// at this point, I expect to be in room E
	// currentRoom = nextRoom(currentRoom, 'east');
	// at this point, I expect to be in room F

	// console.log(start);
	// console.log(finish);
	console.log(currentRoom);
});

var findStartRoom = function(rooms){
	var resultRoom;
	rooms.forEach(function(room) {
		if (room.entrance !== undefined) {
			resultRoom = room;
		}
	});
	return resultRoom;
};

var findFinishRoom = function(rooms){
	var resultRoom;
	rooms.forEach(function(room) {
		if (room.treasure === true) {
			resultRoom = room;
		}
	});
	return resultRoom;
};

var nextRoom = function(currentRoom, direction) {
	 direction = 'north';
	var resultRoom;
	if (direction === 'north') {
		resultRoom = currentRoom.north;
	}
	return resultRoom;
};

rl.close();

// rl.question("You are in a room ", function() {
// });
