#!/usr/bin/env node
'use strict';
var readline = require('readline');
var fs = require('fs');
var file = process.argv[2];
var options = { encoding: 'utf8' };


var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


// save the start room as the current location
// move from the current location north
// save the resulting room as the current location
// move from the currentlocation east
// at this point, I expect to be in room F

var start = entry();
var finish = end();
var currentRoom = start;
currentRoom = moving(currentRoom, 'north');
currentRoom = moving(currentRoom, 'east');


fs.readFile(file, options, function (err, contents){
	var obj = JSON.parse(contents);
//	console.log(obj);
	var start = entry(obj.rooms);
	var finish = end(obj.rooms);
	console.log(start);
	console.log(finish);
	console.log(moving());
	var userResponse = "north";

});
// ['this', 'is', 'an', 'array'].forEach(function(item) {
// });

var entry = function(obj){
	var start;
	obj.forEach(function(room) {
		if (room.entrance !== undefined) {
			start = room;
		}
	});
	return start;
};
var end = function(obj){
	var finish;
	obj.forEach(function(room) {
		if (room.treasure === true) {
			finish = room;
		}
	});
	return finish;
};

var moving = function(obj){
	var userResponse;
	var start;
	var currentRoom;
	if (userResponse === "north"){
		currentRoom = start.north;
	}
	return currentRoom;
};

// var currentRoom = function(obj){

// }

 rl.close();

// rl.question("You are in a room ", function() {
// });


